#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Jupyter datascience build images template

on:
  workflow_call:
    inputs:
      python_dev_tag:
        description: Tag to use for latest base images (foundation, minimal, etc)
        required: true
        type: string
      publish_to_registry:
        description: Wheter to push to the registry
        required: false
        type: string
        default: "false"
      registry:
        description: The list of tags space separated values
        required: false
        type: string
      git_latest_release_tag:
        description: The latest remote release tag 
        required: false
        type: string
        default: ""

jobs:
  r:
    uses: ./.github/workflows/build-multi-arch-image-template.yml
    with:
      parent-image: minimal-notebook:${{ inputs.python_dev_tag }}
      image: r-notebook:${{ inputs.python_dev_tag }}
      registry: ${{ inputs.registry }}
      publish_to_registry: ${{ inputs.publish_to_registry }}
      git_latest_release_tag: ${{ inputs.git_latest_release_tag }}
    secrets: inherit

  datascience:
    uses: ./.github/workflows/build-multi-arch-image-template.yml
    with:
      parent-image: scipy-notebook:${{ inputs.python_dev_tag }}
      image: datascience-notebook:${{ inputs.python_dev_tag }}
      registry: ${{ inputs.registry }}
      publish_to_registry: ${{ inputs.publish_to_registry }}
      git_latest_release_tag: ${{ inputs.git_latest_release_tag }}
    secrets: inherit

  # julia:
  #   uses: ./.github/workflows/build-multi-arch-image-template.yml
  #   with:
  #     parent-image: minimal-notebook:${{ inputs.python_dev_tag }}
  #     image: julia-notebook
  #     registry: ${{ inputs.registry }}
  #     publish_to_registry: ${{ inputs.publish_to_registry }}
  #     git_latest_release_tag: ${{ inputs.git_latest_release_tag }}
  #   secrets: inherit

  # tensorflow:
  #   uses: ./.github/workflows/build-multi-arch-image-template.yml
  #   with:
  #     parent-image: scipy-notebook:${{ inputs.python_dev_tag }}
  #     image: tensorflow-notebook
  #     registry: ${{ inputs.registry }}
  #     publish_to_registry: ${{ inputs.publish_to_registry }}
  #     git_latest_release_tag: ${{ inputs.git_latest_release_tag }}
  #   secrets: inherit

  # pytorch:
  #   uses: ./.github/workflows/build-multi-arch-image-template.yml
  #   with:
  #     parent-image: scipy-notebook:${{ inputs.python_dev_tag }}
  #     image: pytorch-notebook
  #     registry: ${{ inputs.registry }}
  #     publish_to_registry: ${{ inputs.publish_to_registry }}
  #     git_latest_release_tag: ${{ inputs.git_latest_release_tag }}
  #   secrets: inherit






